// SPDX-License-Identifier: Apache-2.0
import React,{useEffect,useRef,useState} from 'react';
import {controlAPI} from './control-api.js';
import {Link} from './navigation.jsx';
import OperatorGuide from './operator-guide.jsx';
import {aggregateTelemetry,preferNewerDelivery,roomTelemetry,runtimeModes} from './telemetry.js';
import {QueueMetrics,RoomHealth,useObservationClock} from './telemetry.jsx';

export default function Dashboard({persistent,canWrite,csrf,session}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[commandError,setCommandError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[refreshKey,setRefreshKey]=useState(0),[updatedAt,setUpdatedAt]=useState(null);
  const heading=useRef(null),mounted=useRef(true),lock=useRef(false),pending=useRef(null);
  const now=useObservationClock();
  const canOperate=Boolean(csrf)&&session?.capabilities.some(capability=>capability.action==='runtime.operate'&&!capability.requiresReauthentication);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{heading.current?.focus();},[]);
  useEffect(()=>{let live=true,timer;async function refresh(){try{const [draft,delivery]=await Promise.all([controlAPI('/config/draft'),persistent?controlAPI('/config/delivery'):null]);if(live){setData(previous=>({draft:draft.data,delivery:delivery?preferNewerDelivery(previous?.delivery,delivery.data):null}));setUpdatedAt(Date.now());setError('');}}catch(e){if(live)setError(e.message);}if(live)timer=setTimeout(refresh,5000);}refresh();return()=>{live=false;clearTimeout(timer);};},[persistent,refreshKey]);
  async function modeCommand(room,runtime,action){
    if(lock.current||!canOperate)return;lock.current=true;setBusy(true);setCommandError('');setNotice('');
    const signature=`${room.id}:${runtime.revision}:${action}`;if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};
    try{await controlAPI(`/rooms/${room.id}/runtime`,{method:'PATCH',body:{action},csrf,etag:`"runtime-${runtime.revision}"`,key:pending.current.key});pending.current=null;if(mounted.current)setNotice(`${room.name}의 ${action==='hold'?'입장 잠시 멈춤':'입장 시작'} 명령을 저장했습니다. 서비스에 반영되는지 확인 중입니다.`);try{const out=await controlAPI('/config/delivery');if(mounted.current){setData(previous=>({...previous,delivery:preferNewerDelivery(previous?.delivery,out.data)}));setUpdatedAt(Date.now());setError('');}}catch(e){if(mounted.current)setError(e.message);}}
    catch(e){if(mounted.current)setCommandError(e.message);}finally{lock.current=false;if(mounted.current)setBusy(false);}
  }
  const delivery=data?.delivery,telemetry=aggregateTelemetry(delivery,{unavailable:Boolean(error),now}),rooms=data?[...(delivery?.config.rooms??[]),...data.draft.rooms.filter(room=>!delivery?.config.rooms.some(published=>published.id===room.id))]:[];
  return <section className="control-workspace ops-dashboard"><div className="ops-header"><div><h2 ref={heading} tabIndex={-1}>대시보드</h2><p>누가 기다리고 있는지 확인하고, 대기열별 입장을 시작하거나 멈춰 보세요.</p></div><div className="ops-header-actions"><button type="button" className="ops-refresh" onClick={()=>setRefreshKey(value=>value+1)} disabled={busy}>새로고침</button>{canWrite?<Link className="ops-primary-link" to="/rooms/new">+ 새 대기열 만들기</Link>:null}</div></div>
    <OperatorGuide/><div className="ops-live-line"><span><i aria-hidden="true"/>{persistent?'5초마다 자동 갱신':'인증 개발 Lab'}</span>{updatedAt?<span>마지막 조회 {new Date(updatedAt).toLocaleTimeString('ko-KR')}</span>:null}{persistent&&data?<span>상태 확인 {telemetry.observedRooms}/{telemetry.rooms.length}개 대기열</span>:null}</div>
    {error?<p role="alert" className="error">{error} · 최신 관측값을 확인할 수 없어 지표와 모드 변경을 잠시 사용할 수 없습니다.</p>:null}
    {commandError?<p role="alert" className="error">{commandError}</p>:null}{notice?<p role="status" className="control-success">{notice}</p>:null}
    {!data?<p role="status">{error?'운영 상태를 표시할 수 없습니다. 새로고침으로 다시 확인하세요.':'운영 상태 불러오는 중…'}</p>:<>
      {persistent?<><QueueMetrics data={telemetry}/><p className="ops-description">운영 중인 모든 대기열의 합계입니다. 유효 입장권은 현재 접속자 수와 다르며, 창을 닫아도 만료까지 유지됩니다.</p></>:<p className="ops-empty">이 인증 Lab에는 Gateway·Coordinator가 연결되지 않습니다. 실제 대기열 지표와 모드 제어는 로컬 Docker 설치에서 사용할 수 있습니다.</p>}
      {persistent&&telemetry.issues.length?<section className="ops-issues" aria-label="확인이 필요한 상태"><h3>확인이 필요한 상태 · {telemetry.issues.length}건</h3><ul>{telemetry.issues.slice(0,8).map((issue,index)=><li key={`${issue.roomId}-${index}`}><Link to={`/rooms/${issue.roomId}/operations`}>{issue.roomName}</Link> · {issue.message}</li>)}</ul>{telemetry.issues.length>8?<p>이외 {telemetry.issues.length-8}건은 각 대기열 운영 화면에서 확인하세요.</p>:null}</section>:null}
      <div className="ops-system-grid"><section className="control-card"><h3>서비스 연결 상태</h3>{persistent?<>{['gateway','coordinator'].map(id=>{const node=delivery?.nodes.find(item=>item.id===id),fresh=!error&&node?.fresh&&node.generation===delivery.generation&&Date.now()-Date.parse(node.observedAt)<=15000;return <div className="ops-service-row" key={id}><div><strong>{id==='gateway'?'방문자 접속 처리':'대기 순서 처리'}</strong><small>{node?`마지막 응답 ${new Date(node.observedAt).toLocaleTimeString('ko-KR')}`:'아직 서비스 응답이 없습니다.'}</small></div><span className={`ops-health-tag ${fresh?'is-good':'is-unknown'}`}>{fresh?'최근 응답':error?'조회 실패':node?'적용 확인 필요':'응답 없음'}</span></div>;})}<div className="ops-service-row"><div><strong>실제 서비스 연결</strong><small>설정한 서비스 주소의 응답 상태</small></div><span>정상 {telemetry.healthyOrigins} · 실패 {telemetry.failedOrigins} · 미확인 {telemetry.unknownOrigins}</span></div><div className="ops-service-row"><div><strong>서버 오류 · 최근 1분</strong><small>방문자 요청을 처리하다 발생한 서버 오류</small></div><span className={`ops-health-tag ${telemetry.http5xx>0?'is-bad':telemetry.http5xx===null?'is-unknown':'is-good'}`}>{telemetry.http5xx===null?(telemetry.http5xxCollecting?'집계 중':'미확인'):`${telemetry.http5xx.toLocaleString('ko-KR')}건`}</span></div></>:<p>실제 서비스 관측은 로컬 Docker 설치에서 제공합니다.</p>}</section>
        <section className="control-card"><h3>설정 상태</h3><div className="ops-service-row"><div><strong>저장한 설정</strong><small>{data.draft.rooms.length}개 대기열</small></div><span>{!persistent?'저장 완료':error?'확인 필요':delivery?.revision===data.draft.revision?'최근 적용 요청한 설정':'적용 전 변경 있음'}</span></div><div className="ops-service-row"><div><strong>서비스에 적용한 설정</strong><small>{persistent?`${delivery?.config.rooms.length??0}개 대기열`:'이 Lab에는 실제 배포가 없습니다.'}</small></div><span>{persistent?(!error&&delivery?.state==='applied'?'적용 확인 완료':'적용 확인 중'):'미연결'}</span></div><p>{persistent&&!error&&delivery?.state==='applied'?'서비스에 설정이 반영됐습니다.':'적용 상태를 확인해야 합니다.'} 저장한 변경을 운영에 반영하려면 아래에서 적용해 주세요.</p>{persistent?<Link className="ops-primary-link" to="/dashboard/runtime">설정 적용하기 →</Link>:null}</section>
      </div>
      <div className="ops-rooms-heading"><h3>대기열 목록 · {rooms.length}개</h3><span>운영 중 / 설정 준비</span></div>
      {rooms.length===0?<p className="ops-empty">아직 대기열이 없습니다. ‘새 대기열 만들기’로 시작하세요.</p>:<ul className="ops-room-grid">{rooms.map(room=>{const observed=roomTelemetry(delivery,room.id,{unavailable:Boolean(error)}),runtime=observed.runtime,isDraft=!runtime;return <li className="ops-room" key={room.id}><div className="ops-room-title"><div><Link to={`/rooms/${room.id}/${isDraft?'settings':'operations'}`}>{room.name}</Link><p>{room.hostname}</p></div><span>{isDraft?'설정 준비':'운영에 적용됨'}</span></div>{isDraft?<p className="ops-empty">설정을 저장한 상태입니다. ‘서비스에 적용’을 진행하면 입장을 운영할 수 있어요.</p>:<><p className="ops-room-mode">{observed.mode?runtimeModes[observed.mode]:'서비스 모드 확인 불가'}<span>선택한 방식: {runtimeModes[runtime.mode]} · {observed.applied?'적용 완료':'적용 확인 중'}</span></p><RoomHealth data={observed}/><QueueMetrics data={observed} compact/></>}
          <div className="ops-room-actions">{canOperate&&!isDraft?<><button type="button" disabled={busy||!room.active||!observed.coordinator.usable||!observed.gateway.usable} aria-pressed={runtime.mode==='HOLD'} onClick={()=>modeCommand(room,runtime,'hold')} aria-label={`${room.name} 입장 잠시 멈춤`}>입장 잠시 멈춤</button><button type="button" disabled={busy||!room.active||!observed.coordinator.usable||!observed.gateway.usable} aria-pressed={runtime.mode==='AUTO'} onClick={()=>modeCommand(room,runtime,'auto')} aria-label={`${room.name} 입장 시작`}>입장 시작</button></>:null}<Link to={`/rooms/${room.id}/${isDraft?'settings':'operations'}`}>{isDraft?'설정 수정':'입장 운영'} →</Link></div>
        </li>;})}</ul>}
      {canOperate&&persistent?<p className="ops-description">‘입장 잠시 멈춤’은 새 입장만 멈추며 이미 받은 입장권은 유지됩니다. ‘입장 시작’은 설정한 인원 안에서 순서대로 입장시킵니다. 직접 변경하면 자동 예약은 일시정지됩니다.</p>:null}
    </>}
  </section>;
}
