// SPDX-License-Identifier: Apache-2.0
import React,{useEffect,useRef,useState} from 'react';
import {controlAPI} from './control-api.js';
import {Link} from './navigation.jsx';
import {aggregateTelemetry,preferNewerDelivery,roomTelemetry,runtimeModes} from './telemetry.js';
import {QueueMetrics,RoomHealth,useObservationClock} from './telemetry.jsx';

export default function Dashboard({persistent,canWrite,csrf,session}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[commandError,setCommandError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[refreshKey,setRefreshKey]=useState(0),[updatedAt,setUpdatedAt]=useState(null);
  const heading=useRef(null),mounted=useRef(true),lock=useRef(false),pending=useRef(null);
  const now=useObservationClock();
  const canOperate=Boolean(csrf)&&session?.capabilities.some(capability=>capability.action==='runtime.operate'&&!capability.requiresReauthentication);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{heading.current?.focus();},[]);
  useEffect(()=>{let live=true,timer;async function refresh(){try{const [draft,delivery]=await Promise.all([controlAPI('/config/draft'),persistent?controlAPI('/config/delivery'):null]);if(live){setData(previous=>({draft:draft.data,delivery:delivery?preferNewerDelivery(previous?.delivery,delivery.data):null}));setUpdatedAt(Date.now());setError('');}}catch(e){if(live)setError(e.message);}if(live)timer=setTimeout(refresh,5000);}refresh();return()=>{live=false;clearTimeout(timer);};},[persistent,refreshKey]);
  async function modeCommand(room,runtime,action){
    if(lock.current||!canOperate)return;lock.current=true;setBusy(true);setCommandError('');setNotice('');
    const signature=`${room.id}:${runtime.revision}:${action}`;if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};
    try{await controlAPI(`/rooms/${room.id}/runtime`,{method:'PATCH',body:{action},csrf,etag:`"runtime-${runtime.revision}"`,key:pending.current.key});pending.current=null;if(mounted.current)setNotice(`${room.name}의 ${action==='hold'?'HOLD':'AUTO'} 명령을 저장했습니다. Gateway와 Coordinator의 적용 상태를 확인 중입니다.`);try{const out=await controlAPI('/config/delivery');if(mounted.current){setData(previous=>({...previous,delivery:preferNewerDelivery(previous?.delivery,out.data)}));setUpdatedAt(Date.now());setError('');}}catch(e){if(mounted.current)setError(e.message);}}
    catch(e){if(mounted.current)setCommandError(e.message);}finally{lock.current=false;if(mounted.current)setBusy(false);}
  }
  const delivery=data?.delivery,telemetry=aggregateTelemetry(delivery,{unavailable:Boolean(error),now}),rooms=data?[...(delivery?.config.rooms??[]),...data.draft.rooms.filter(room=>!delivery?.config.rooms.some(published=>published.id===room.id))]:[];
  return <section className="control-workspace ops-dashboard"><div className="ops-header"><div><h2 ref={heading} tabIndex={-1}>대시보드</h2><p>대기 흐름과 서비스 상태를 확인하고, Room별 입장을 제어하세요.</p></div><div className="ops-header-actions"><button type="button" className="ops-refresh" onClick={()=>setRefreshKey(value=>value+1)} disabled={busy}>새로고침</button>{canWrite?<Link className="ops-primary-link" to="/rooms/new">+ 새 Room 만들기</Link>:null}</div></div>
    <div className="ops-live-line"><span><i aria-hidden="true"/>{persistent?'5초마다 자동 갱신':'인증 개발 Lab'}</span>{updatedAt?<span>마지막 조회 {new Date(updatedAt).toLocaleTimeString('ko-KR')}</span>:null}{persistent&&data?<span>최신 서비스 관측 {telemetry.observedRooms}/{telemetry.rooms.length} Room</span>:null}</div>
    {error?<p role="alert" className="error">{error} · 최신 관측값을 확인할 수 없어 지표와 모드 변경을 잠시 사용할 수 없습니다.</p>:null}
    {commandError?<p role="alert" className="error">{commandError}</p>:null}{notice?<p role="status" className="control-success">{notice}</p>:null}
    {!data?<p role="status">{error?'운영 상태를 표시할 수 없습니다. 새로고침으로 다시 확인하세요.':'운영 상태 불러오는 중…'}</p>:<>
      {persistent?<><QueueMetrics data={telemetry}/><p className="ops-description">배포된 전체 Room의 최신 Coordinator 관측값입니다. 입장 완료는 READY를 제외한 유효 입장권 수이며 현재 접속자 수가 아닙니다. 실제 입장 배정은 최근 60초의 READY 예약 발급 수입니다.</p></>:<p className="ops-empty">이 인증 Lab에는 Gateway·Coordinator가 연결되지 않습니다. 실제 대기열 지표와 모드 제어는 로컬 Docker 설치에서 사용할 수 있습니다.</p>}
      {persistent&&telemetry.issues.length?<section className="ops-issues" aria-label="확인이 필요한 상태"><h3>확인이 필요한 상태 · {telemetry.issues.length}건</h3><ul>{telemetry.issues.slice(0,8).map((issue,index)=><li key={`${issue.roomId}-${index}`}><Link to={`/rooms/${issue.roomId}/operations`}>{issue.roomName}</Link> · {issue.message}</li>)}</ul>{telemetry.issues.length>8?<p>이외 {telemetry.issues.length-8}건은 Room별 운영 화면에서 확인하세요.</p>:null}</section>:null}
      <div className="ops-system-grid"><section className="control-card"><h3>서비스 건강 상태</h3>{persistent?<>{['gateway','coordinator'].map(id=>{const node=delivery?.nodes.find(item=>item.id===id),fresh=!error&&node?.fresh&&node.generation===delivery.generation&&Date.now()-Date.parse(node.observedAt)<=15000;return <div className="ops-service-row" key={id}><div><strong>{id==='gateway'?'Gateway':'Coordinator'}</strong><small>{node?`마지막 응답 ${new Date(node.observedAt).toLocaleTimeString('ko-KR')} · generation ${node.generation}`:'아직 서비스 응답이 없습니다.'}</small></div><span className={`ops-health-tag ${fresh?'is-good':'is-unknown'}`}>{fresh?'최근 응답':error?'조회 실패':node?'적용 확인 필요':'응답 없음'}</span></div>;})}<div className="ops-service-row"><div><strong>원본 연결</strong><small>Gateway의 상태 확인 URL 검사 결과</small></div><span>정상 {telemetry.healthyOrigins} · 실패 {telemetry.failedOrigins} · 미확인 {telemetry.unknownOrigins}</span></div><div className="ops-service-row"><div><strong>HTTP 5xx · 최근 60초</strong><small>Gateway가 관측한 Room 요청의 최종 오류 응답</small></div><span className={`ops-health-tag ${telemetry.http5xx>0?'is-bad':telemetry.http5xx===null?'is-unknown':'is-good'}`}>{telemetry.http5xx===null?(telemetry.http5xxCollecting?'관측 창 수집 중':'미확인'):`${telemetry.http5xx.toLocaleString('ko-KR')}건`}</span></div></>:<p>실제 서비스 관측은 로컬 Docker 설치에서 제공합니다.</p>}</section>
        <section className="control-card"><h3>설정 상태</h3><div className="ops-service-row"><div><strong>저장된 초안</strong><small>{data.draft.rooms.length}개 Room</small></div><span>revision {data.draft.revision}</span></div><div className="ops-service-row"><div><strong>배포 설정</strong><small>{persistent?`${delivery?.config.rooms.length??0}개 Room · generation ${delivery?.generation??'—'}`:'이 Lab에는 실제 배포가 없습니다.'}</small></div><span>{persistent?`revision ${delivery?.revision??'—'}`:'미연결'}</span></div><p>{persistent&&!error&&delivery?.state==='applied'?'두 서비스가 배포 설정에 응답했습니다.':'적용 상태를 확인해야 합니다.'} 초안 저장만으로는 실제 운영 설정이 바뀌지 않습니다.</p>{persistent?<Link className="ops-primary-link" to="/dashboard/runtime">배포와 적용 상태 확인 →</Link>:null}</section>
      </div>
      <div className="ops-rooms-heading"><h3>Room 목록 · {rooms.length}개</h3><span>실제 운영 / 초안</span></div>
      {rooms.length===0?<p className="ops-empty">아직 Room이 없습니다. 연결 정보와 보호 경로부터 준비하세요.</p>:<ul className="ops-room-grid">{rooms.map(room=>{const observed=roomTelemetry(delivery,room.id,{unavailable:Boolean(error)}),runtime=observed.runtime,isDraft=!runtime;return <li className="ops-room" key={room.id}><div className="ops-room-title"><div><Link to={`/rooms/${room.id}/${isDraft?'settings':'operations'}`}>{room.name}</Link><p>{room.hostname}</p></div><span>{isDraft?'초안':'배포됨'}</span></div>{isDraft?<p className="ops-empty">아직 운영에 배포되지 않았습니다. 설정을 검토하고 배포를 진행하세요.</p>:<><p className="ops-room-mode">{observed.mode?runtimeModes[observed.mode]:'서비스 모드 확인 불가'}<span>저장된 명령 {runtime.mode} · revision {runtime.revision}</span></p><RoomHealth data={observed}/><QueueMetrics data={observed} compact/></>}
          <div className="ops-room-actions">{canOperate&&!isDraft?<><button type="button" disabled={busy||!room.active||!observed.coordinator.usable||!observed.gateway.usable} onClick={()=>modeCommand(room,runtime,'hold')} aria-label={`${room.name} HOLD 일시정지`}>HOLD 일시정지</button><button type="button" disabled={busy||!room.active||!observed.coordinator.usable||!observed.gateway.usable} onClick={()=>modeCommand(room,runtime,'auto')} aria-label={`${room.name} AUTO 시작`}>AUTO 시작</button></>:null}<Link to={`/rooms/${room.id}/${isDraft?'settings':'operations'}`}>{isDraft?'초안 편집':'운영 상세'} →</Link></div>
        </li>;})}</ul>}
      {canOperate&&persistent?<p className="ops-description">HOLD는 신규 입장 배정을 멈추고 기존 입장권을 유지합니다. AUTO는 설정된 한도 안에서 순서대로 입장 예약을 배정합니다. 수동 모드 변경은 해당 Room의 예약 일정을 일시정지합니다.</p>:null}
    </>}
  </section>;
}
