// SPDX-License-Identifier: Apache-2.0
import React,{useEffect,useState} from 'react';
import {runtimeModes} from './telemetry.js';
import './telemetry.css';
const display=value=>value===null?'—':Number(value).toLocaleString('ko-KR');
export function useObservationClock(){const [now,setNow]=useState(Date.now);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);return now;}
export function QueueMetrics({data,compact=false}){return <div className={`ops-metrics${compact?' ops-metrics-compact':''}`} aria-label="대기열 관측 지표">{[['waiting','대기 중','입장 순서 확인 중','아직 입장 순서를 기다리는 대기표'],['ready','입장 준비','곧 입장 가능','입장 가능 안내를 받은 예약'],['admitted','유효 입장권','만료 전 입장권','창을 닫아도 만료까지 유지되는 입장권'],['rate','실제 입장 배정','최근 60초','최근 60초 동안 배정한 입장 예약']].map(([field,title,label,hint])=><div className={`ops-metric ops-metric-${field}`} key={field}><div><strong>{title}</strong><span>{label}</span></div><p>{display(data[field])}<small>{field==='rate'?'건':'개'}</small></p>{!compact?<span className="ops-metric-hint">{data[field]===null?'최신 관측값 없음':hint}</span>:null}</div>)}</div>;}
export function RoomHealth({data}){return <div className="ops-room-health"><span className={`ops-health-tag ${data.originHealthy===true?'is-good':data.originHealthy===false?'is-bad':'is-unknown'}`}><i aria-hidden="true"/>서비스 {data.originHealthy===true?'정상':data.originHealthy===false?'응답 실패':'미확인'}</span><span className={`ops-health-tag ${data.applied?'is-good':'is-unknown'}`}>{data.applied?'설정 적용 완료':'설정 적용 확인 중'}</span><span className={`ops-health-tag ${data.http5xx>0?'is-bad':data.http5xx===null?'is-unknown':'is-good'}`}>서버 오류 · 최근 1분 {data.http5xx===null?(data.http5xxCollecting?'수집 중':'미확인'):`${display(data.http5xx)}건`}</span></div>;}
export function RuntimeState({data}){return <div className="ops-runtime-state"><div><span>실제로 적용된 상태</span><strong>{data.mode?runtimeModes[data.mode]??data.mode:'확인할 수 없음'}</strong></div><div><span>선택한 운영 방식</span><strong>{runtimeModes[data.runtime?.mode]??'미배포'}</strong></div><div><span>1분당 입장 제한</span><strong>{data.runtime?`${display(data.runtime.limits.admissionsPerMinute)}명 / 분`:'—'}</strong></div></div>;}
